package com.security.idsips.detection;

import jakarta.persistence.*;
import java.time.LocalDateTime;

/**
 * Entity representing a security alert generated by the detection engine
 */
@Entity
@Table(name = "security_alerts")
public class SecurityAlert {
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    @Column(unique = true, nullable = false)
    private String alertId;
    
    @Column(nullable = false)
    private LocalDateTime timestamp;
    
    @Column(nullable = false)
    private String sourceIp;
    
    @Column(nullable = false)
    private String destinationIp;
    
    private Integer sourcePort;
    private Integer destinationPort;
    private String protocol;
    
    @Column(nullable = false)
    @Enumerated(EnumType.STRING)
    private AlertSeverity severity;
    
    @Column(nullable = false)
    @Enumerated(EnumType.STRING)
    private AlertType alertType;
    
    @Column(nullable = false, length = 1000)
    private String description;
    
    @Column(columnDefinition = "TEXT")
    private String encryptedDetails;
    
    @Column(nullable = false)
    @Enumerated(EnumType.STRING)
    private AlertStatus status;
    
    private LocalDateTime resolvedAt;
    private String resolvedBy;
    
    // Constructors
    public SecurityAlert() {
        this.timestamp = LocalDateTime.now();
        this.status = AlertStatus.OPEN;
    }
    
    public SecurityAlert(String alertId, String sourceIp, String destinationIp, 
                        AlertSeverity severity, AlertType alertType, String description) {
        this();
        this.alertId = alertId;
        this.sourceIp = sourceIp;
        this.destinationIp = destinationIp;
        this.severity = severity;
        this.alertType = alertType;
        this.description = description;
    }
    
    // Getters and Setters
    public Long getId() {
        return id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    public String getAlertId() {
        return alertId;
    }
    
    public void setAlertId(String alertId) {
        this.alertId = alertId;
    }
    
    public LocalDateTime getTimestamp() {
        return timestamp;
    }
    
    public void setTimestamp(LocalDateTime timestamp) {
        this.timestamp = timestamp;
    }
    
    public String getSourceIp() {
        return sourceIp;
    }
    
    public void setSourceIp(String sourceIp) {
        this.sourceIp = sourceIp;
    }
    
    public String getDestinationIp() {
        return destinationIp;
    }
    
    public void setDestinationIp(String destinationIp) {
        this.destinationIp = destinationIp;
    }
    
    public Integer getSourcePort() {
        return sourcePort;
    }
    
    public void setSourcePort(Integer sourcePort) {
        this.sourcePort = sourcePort;
    }
    
    public Integer getDestinationPort() {
        return destinationPort;
    }
    
    public void setDestinationPort(Integer destinationPort) {
        this.destinationPort = destinationPort;
    }
    
    public String getProtocol() {
        return protocol;
    }
    
    public void setProtocol(String protocol) {
        this.protocol = protocol;
    }
    
    public AlertSeverity getSeverity() {
        return severity;
    }
    
    public void setSeverity(AlertSeverity severity) {
        this.severity = severity;
    }
    
    public AlertType getAlertType() {
        return alertType;
    }
    
    public void setAlertType(AlertType alertType) {
        this.alertType = alertType;
    }
    
    public String getDescription() {
        return description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    public String getEncryptedDetails() {
        return encryptedDetails;
    }
    
    public void setEncryptedDetails(String encryptedDetails) {
        this.encryptedDetails = encryptedDetails;
    }
    
    public AlertStatus getStatus() {
        return status;
    }
    
    public void setStatus(AlertStatus status) {
        this.status = status;
    }
    
    public LocalDateTime getResolvedAt() {
        return resolvedAt;
    }
    
    public void setResolvedAt(LocalDateTime resolvedAt) {
        this.resolvedAt = resolvedAt;
    }
    
    public String getResolvedBy() {
        return resolvedBy;
    }
    
    public void setResolvedBy(String resolvedBy) {
        this.resolvedBy = resolvedBy;
    }
    
    // Enums
    public enum AlertSeverity {
        LOW, MEDIUM, HIGH, CRITICAL
    }
    
    public enum AlertType {
        PORT_SCAN, BRUTE_FORCE, MALICIOUS_PAYLOAD, SUSPICIOUS_TRAFFIC, 
        ANOMALOUS_BEHAVIOR, UNAUTHORIZED_ACCESS, DDoS_ATTACK
    }
    
    public enum AlertStatus {
        OPEN, INVESTIGATING, RESOLVED, FALSE_POSITIVE
    }
    
    @Override
    public String toString() {
        return String.format("SecurityAlert{id='%s', type=%s, severity=%s, %s:%d -> %s:%d, desc='%s'}", 
                           alertId, alertType, severity, sourceIp, sourcePort, 
                           destinationIp, destinationPort, description);
    }
}
